name: Build, tag, push local dev environment image

on:
  workflow_dispatch:

jobs:
  update-local-dev-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/bake-action@v3
        with:
          file: ./local-dev-env-image/docker-compose.yml
          push: true
          tags: rianfowler/glowing-system-dev-env-test:latest

