services:
  app:
    user: root
    entrypoint:
    - sleep
    - infinity
    image: rianfowler/glowing-system-dev-env:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sockservices:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
