services:
  app-OPEN-THIS-IN-VSCODE-FIRST:
    user: root
    entrypoint:
    - sleep
    - infinity
    image: rianfowler/glowing-system-dev-env:latest
    pull_policy: always
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fistbumppw
      POSTGRES_USER: fistbumpdev
      POSTGRES_DB: fistbumpdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
