version: '3'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: rianfowler/base:latest

  gorilla:
    build:
      context: .
      dockerfile: Dockerfile.gorilla
    image: rianfowler/gorilla:latest