version: '3'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base:latest

  gorilla:
    build:
      context: .
      dockerfile: Dockerfile.gorilla
    image: gorilla:latest

