apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app-deployment
  labels:
    app: next-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: rianfowler/next-app:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 3000
