name: Build and Tag Development Image

on:
  workflow_dispatch:

jobs:
  build-tag-push-dev-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rianfowler/next-app:${{ github.sha }}

      - name: Update Chart.yaml and push to main
        id: chart-update
        run: |
          # Install yq for editing YAML files
          sudo snap install yq

          # Extract current versions
          current_app_version=$(yq e '.appVersion' charts/next-app-chart/Chart.yaml)
          current_chart_version=$(yq e '.version' charts/next-app-chart/Chart.yaml)

          # Set new app version
          yq e -i '.appVersion = "${{ github.sha }}"' charts/next-app-chart/Chart.yaml

          # Set new chart version
          if [[ $current_chart_version == *"-alpha."* ]]; then
            current_alpha_version=$(echo $current_chart_version | grep -o 'alpha.[0-9]*' | sed 's/alpha.//')
            new_alpha_version=$((current_alpha_version+1))
            new_chart_version=$(echo $current_chart_version | sed "s/alpha.$current_alpha_version/alpha.$new_alpha_version/")
          else
            new_chart_version="$current_chart_version-alpha.1"
          fi

          yq e -i ".version = \"$new_chart_version\"" charts/next-app-chart/Chart.yaml

          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add charts/next-app-chart/Chart.yaml
          git commit -m "Update Chart version to $new_chart_version"
          git push

