name: Build and Tag Development Image

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image for ARM and AMD
        env:
          DOCKER_BUILDKIT: 1
        run: |
          version=${{ github.sha }}
          docker buildx build --platform linux/arm64,linux/amd64 -t rianfowler/next-app:$version .
          docker tag rianfowler/next-app:$version rianfowler/next-app:latest-dev
          docker push rianfowler/next-app:$version
          docker push rianfowler/next-app:latest-dev
