name: Build & Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Choose version update type'
        required: true
        default: 'patch'
        options: ['patch', 'minor', 'major']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          version=${{ github.sha }}
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            version_type=${{ github.event.inputs.version-type }}
            if [[ "$version_type" == "patch" || "$version_type" == "minor" || "$version_type" == "major" ]]; then
              version=$(date -u +"%Y%m%d%H%M%S")
              echo "Version type: $version_type"
              echo "New version: $version"
            fi
          fi
          docker buildx build --platform linux/arm64,linux/amd64 -t rianfowler/next-app:$version .
      
      - name: Tag Docker image with latest-dev
        run: docker tag rianfowler/next-app:$version rianfowler/next-app:latest-dev

      - name: Push Docker images
        run: |
          docker push rianfowler/next-app:$version
          docker push rianfowler/next-app:latest-dev
