name: update-helm-repo

on:
  workflow_run:
    workflows: ["update-app-image"]
    types:
      - completed

jobs:
  update-helm-repo:
    runs-on: ubuntu-latest
    if: ${{ github.event.act || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Checkout source repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: glowing-system
        ref: main

    - name: Clone target repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        repository: titan-syndicate/glowing-system-charts
        path: glowing-system-charts

    - name: Check for existing version in target repo
      run: |
        cd $GITHUB_WORKSPACE/glowing-system
        NEW_VERSION=$(helm show chart charts/next-app-chart | grep version | cut -d: -f2 | tr -d ' ')
        cd $GITHUB_WORKSPACE/glowing-system-charts
        if grep -q "version: $NEW_VERSION" index.yaml; then
          echo "Error: Chart version $NEW_VERSION already exists. Increment the version before pushing!"
          exit 1
        fi

    - name: Lint and Package Helm Chart
      run: |
        cd $GITHUB_WORKSPACE/glowing-system
        helm lint charts/next-app-chart
        helm package charts/next-app-chart -d $GITHUB_WORKSPACE/glowing-system-charts

    - name: Commit package to target repo
      run: |
        cd $GITHUB_WORKSPACE/glowing-system-charts
        helm repo index . --url https://titan-syndicate.github.io/glowing-system-charts/
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add -A
        git commit -m "Add new chart version"

    - name: Push to another repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GLOWING_SYSTEM_CHARTS_GITHUB_TOKEN }}
        repository: titan-syndicate/glowing-system-charts

