name: update-helm-repo

on:
  workflow_run:
    workflows: ["update-app-image"]
    types:
      - completed

jobs:
  update-helm-repo:
    runs-on: ubuntu-latest
    if: ${{ env.ACT || github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Clone target repo
      uses: actions/checkout@v3
      with:
        repository: titan-syndicate/glowing-system-charts
        path: glowing-system-charts
        ref: main

    - name: Lint and Package Helm Chart
      run: |
        helm lint charts/next-app-chart
        helm package charts/next-app-chart -d ./glowing-system-charts

    - name: Check for existing version in target repo
      run: |
        cd glowing-system-charts
        NEW_VERSION=$(helm show chart ../charts/next-app-chart | grep version | cut -d: -f2 | tr -d ' ')
        if grep -q "version: $NEW_VERSION" index.yaml; then
          echo "Error: Chart version $NEW_VERSION already exists. Increment the version before pushing!"
          exit 1
        fi

    - name: Copy package to target repo and Update Helm Repo
      run: |
        helm repo index . --url https://titan-syndicate.github.io/glowing-system-charts/

    - name: Push to another repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GLOWING_SYSTEM_CHARTS_GITHUB_TOKEN }}
        repository: titan-syndicate/glowing-system-charts
        branch: main

