name: upgrade-dev-environment

on:
  workflow_run:
    workflows: ["update-helm-repo"]
    types:
      - completed

jobs:
  helm-upgrade-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Set up kubeconfig
      run: |
        echo "$KUBECONFIG_64" | base64 -d > kubeconfig.yaml

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Add Helm Repository
      run: |

        helm repo add titan-syndicate https://titan-syndicate.github.io/glowing-system-charts/
        helm repo update
        helm plugin install https://github.com/titan-syndicate/helm-latest-prerelease

    - name: Install or Upgrade Helm Chart
      run: |
        helm upgrade -i --kubeconfig kubeconfig.yaml glowing-system titan-syndicate/next-app-chart --version=$(helm latest-prerelease titan-syndicate/next-app-chart)

    env:
      KUBECONFIG_64: ${{ secrets.KUBECONFIG_64 }}
