name: Deploy latest to dev with Helm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: mirzakhany/helm-install-action@v1
        with:
          k8s_config: ${{ secrets.KUBECONFIG }}

    - name: Add Helm Repository
      run: |
        helm repo add titan-syndicate https://titan-syndicate.github.io/glowing-system-charts/
        helm repo update

    - name: Install or Upgrade Helm Chart
      run: |
        if helm ls -n default | grep -q glowing-system; then
          helm upgrade glowing-system titan-syndicate/next-app-chart
        else
          helm install glowing-system titan-syndicate/next-app-chart
        fi
